### ISSUE TITLE
add additional options in the XSD_FMT_TYPE_FN

### ISSUE THREAD

**Issue by cedricdcc** [vliz-be-opsci/pyrdfj2#17]
where we fix the omission of 'xsd:' at the start

XSD_FMT_TYPE_FN = {
    "xsd:boolean": xsd_format_boolean,
    "boolean": xsd_format_boolean,
    "xsd:integer": xsd_format_integer,
    "integer": xsd_format_integer,
...
}

**Comment by marc-portier** [comment]
fixed in 9b1450cad8a9bf85a86dc51fcd40ba0b808d23ed
