### ISSUE TITLE
proper URI escaping in ttl

### ISSUE THREAD

**Issue by laurianvm** [vliz-be-opsci/pyrdfj2#18]
Some uri patterns seem to be: 
- acceptable according to ttl / rdf validators
- still not accepted by triples stores as actual `<uri>` identifiers

to avoid these problems we propose 
- [x] to provide a proper way to clean these and make them 'safe to use' (see code example at https://github.com/vliz-be-opsci/py-RDF-store/issues/46 showing how to use urllib's `quote()`)
- [x] to allow calling this from the templates through different ways
  - [x] `| uri` --> make clean + surround in `< .. >`  --> e.g. usage as `{ uritexpand(..) | uri }
  - [x] `| xml("xsd:anyURI") --> make clean and add `" .. "^^xsd:anyURI`

VLIZ internals / follow up - do bump https://vliz.atlassian.net/browse/IMIS-1491 after implementation and tests become available, triggering the update of the twig port

**Comment by marc-portier** [comment]
fixed in combo of fc975398dfb7c61ca157cb3f2d035aa695582cf5 and fcf555e92e67ed3b191dcb88f6fc5f4d099a3b0f
